sculpin_content_types:
    posts:
        permalink: blog/:slug_title

sculpin_twig:
    source_view_paths:
        - _views
        - _layouts
        - _partials
        - _includes
# sculpin:
#     ignore: ["**/*.json", "**/*.md", "**/*.scss", "assets/css/", "assets/js/"]
# To disable posts (e.g., if you aren't planning on having any posts and Sculpin's watch mode complains):
