title: François B.
subtitle: Développeur d'applications utiles et durables. Flutter/Dart
url: http://localhost:5500
disqus:
    shortname: luston-neocities-org

version: dev
version_timestamp: 2024-07-31T23:20:44Z

webmaster:
    birth: 1998-04-06
