name: Build and deploy
on:
  push:
    # Pattern matched against refs/tags
    tags:
      - "*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      COMPOSER_VERSION: 1
      NODE_VERSION: 18

      OVH_SFTP_SERVER: ftp.cluster021.hosting.ovh.net

      REPOSITORY_NAME: fbanitz.fr
      REPOSITORY_URL: https://github.com/fbanitz/fbanitz.fr.git

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get the version
        id: get_version
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Get current datetime
        id: get-datetime
        run: echo "atom=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Update sculpin_site_prod.yml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: "app/config/sculpin_site_prod.yml"
          changes: |
            {
              "version" : "${{ steps.get_version.outputs.tag }}",
              "version_timestamp" : "${{ steps.get-datetime.outputs.atom }}"
            }
          commitChange: false

      - name: Cache Vendor
        id: cache-vendor
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install Yarn
        run: corepack enable

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Build assets
        run: yarn encore:prod

      - name: Verify built assets
        run: |
          if [ ! -f "source/assets/build/app.js" ] || [ ! -f "source/assets/build/app.css" ]; then
            echo "Error: Built assets are missing"
            exit 1
          fi

      - name: Run composer install
        if: steps.cache-vendor.outputs.cache-hit != 'true' # Skip if cache hit
        uses: baschny/php-composer-action@v1
        with:
          composer_version: ${{ env.COMPOSER_VERSION }}
          command: install
          #github_oauth: ${{ secret.GITHUB_OAUTH }}

      - name: Generate with Scuplpin
        run: |
          mkdir -p source/assets/build
          vendor/bin/sculpin generate --env=prod

      - name: Check output files size
        uses: freenet-actions/check-file-size@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: output_prod
          max_size: 250
          post_comment: true
          fail_on_find: true

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.REPOSITORY_NAME }}-${{ steps.get_version.outputs.tag }}
          path: output_prod

      - name: SFTP Upload
        uses: Dylan700/sftp-upload-action@v1.2.3
        with:
          server: ${{ env.OVH_SFTP_SERVER }}
          username: ${{ secrets.OVH_SFTP_USER }}
          password: ${{ secrets.OVH_SFTP_PASSWORD }}
          uploads: |
            output_prod/ => /home/${{ secrets.OVH_SFTP_USER }}/www/
          delete: true
